name: CI

on:
    push:
        branches:
            - main
            - develop
    pull_request:

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
    cancel-in-progress: true

permissions:
    contents: read # to fetch code (actions/checkout)

jobs:
    commitlint:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Lint Commits
              uses: wagoid/commitlint-github-action@v5

    codelint:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Node.js Latest
              uses: actions/setup-node@v3
              with:
                  node-version: latest
                  cache: yarn

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Run Linter
              run: yarn run lint

    typescript-check:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Node.js Latest
              uses: actions/setup-node@v3
              with:
                  node-version: latest
                  cache: yarn

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Run TypeScript Check
              run: yarn run check
